In [2]:
import pandas as pd
import numpy as np

In [3]:
path_to_csv = '/home/stanislaw/datasets/ranzcr-clip/train.csv'

In [4]:
train_df = pd.read_csv(path_to_csv)

In [5]:
train_df.head()

StudyInstanceUID  ETT - Abnormal  \
0  1.2.826.0.1.3680043.8.498.26697628953273228189...               0   
1  1.2.826.0.1.3680043.8.498.46302891597398758759...               0   
2  1.2.826.0.1.3680043.8.498.23819260719748494858...               0   
3  1.2.826.0.1.3680043.8.498.68286643202323212801...               0   
4  1.2.826.0.1.3680043.8.498.10050203009225938259...               0   

   ETT - Borderline  ETT - Normal  NGT - Abnormal  NGT - Borderline  \
0                 0             0               0                 0   
1                 0             1               0                 0   
2                 0             0               0                 0   
3                 0             0               0                 0   
4                 0             0               0                 0   

   NGT - Incompletely Imaged  NGT - Normal  CVC - Abnormal  CVC - Borderline  \
0                          0             1               0                 0   
1                          1             0               0                 0   
2                          0             0               0                 1   
3                          0             0               1                 0   
4                          0             0               0                 0   

   CVC - Normal  Swan Ganz Catheter Present  PatientID  
0             0                           0  ec89415d1  
1             1                           0  bf4c6da3c  
2             0                           0  3fc1c97e5  
3             0                           0  c31019814  
4             1                           0  207685cd1

In [6]:
24 / 14000

0.0017142857142857142

In [7]:
len(train_df)

30083

In [8]:
np.random.choice(len(train_df), replace=False)

11214

In [9]:
from collections import OrderedDict, defaultdict

In [10]:
s = train_df.iloc[:, 1:-1].sum()

In [11]:
np.sum(train_df.iloc[:, 1:-1].sum(1) == 1), np.sum(train_df.iloc[:, 1:-1].sum(1) == 0)

(18760, 24)

In [12]:
type(s)

pandas.core.series.Series

In [13]:
s

ETT - Abnormal                   79
ETT - Borderline               1138
ETT - Normal                   7240
NGT - Abnormal                  279
NGT - Borderline                529
NGT - Incompletely Imaged      2748
NGT - Normal                   4797
CVC - Abnormal                 3195
CVC - Borderline               8460
CVC - Normal                  21324
Swan Ganz Catheter Present      830
dtype: int64

In [14]:
s.to_dict(dict())

{'ETT - Abnormal': 79,
 'ETT - Borderline': 1138,
 'ETT - Normal': 7240,
 'NGT - Abnormal': 279,
 'NGT - Borderline': 529,
 'NGT - Incompletely Imaged': 2748,
 'NGT - Normal': 4797,
 'CVC - Abnormal': 3195,
 'CVC - Borderline': 8460,
 'CVC - Normal': 21324,
 'Swan Ganz Catheter Present': 830}

In [15]:
s['None'] = np.sum(train_df.iloc[:, 1:-1].sum(1) == 0)

In [16]:
s

ETT - Abnormal                   79
ETT - Borderline               1138
ETT - Normal                   7240
NGT - Abnormal                  279
NGT - Borderline                529
NGT - Incompletely Imaged      2748
NGT - Normal                   4797
CVC - Abnormal                 3195
CVC - Borderline               8460
CVC - Normal                  21324
Swan Ganz Catheter Present      830
None                             24
dtype: int64

In [17]:
names = s.index.to_list()

In [18]:
counts = s.values

In [19]:
counts / np.sum(counts)

array([0.00155994, 0.02247102, 0.14296151, 0.00550915, 0.01044567,
       0.05426219, 0.09472188, 0.06308868, 0.16705171, 0.4210651 ,
       0.01638923, 0.00047391])

In [20]:
probs = dict(zip(names, counts / np.sum(counts)))

In [21]:
train_df.groupby('PatientID').sum().sum(1).median()

6.0

In [22]:
probs

{'ETT - Abnormal': 0.001559939182117963,
 'ETT - Borderline': 0.022471022648737238,
 'ETT - Normal': 0.14296151491815257,
 'NGT - Abnormal': 0.005509152301403945,
 'NGT - Borderline': 0.010445668700511423,
 'NGT - Incompletely Imaged': 0.054262188258989395,
 'NGT - Normal': 0.09472187666607429,
 'CVC - Abnormal': 0.06308867958059357,
 'CVC - Borderline': 0.16705171494579704,
 'CVC - Normal': 0.4210651027782714,
 'Swan Ganz Catheter Present': 0.016389234445036826,
 'None': 0.0004739055743143179}

In [23]:
train_df.head()

StudyInstanceUID  ETT - Abnormal  \
0  1.2.826.0.1.3680043.8.498.26697628953273228189...               0   
1  1.2.826.0.1.3680043.8.498.46302891597398758759...               0   
2  1.2.826.0.1.3680043.8.498.23819260719748494858...               0   
3  1.2.826.0.1.3680043.8.498.68286643202323212801...               0   
4  1.2.826.0.1.3680043.8.498.10050203009225938259...               0   

   ETT - Borderline  ETT - Normal  NGT - Abnormal  NGT - Borderline  \
0                 0             0               0                 0   
1                 0             1               0                 0   
2                 0             0               0                 0   
3                 0             0               0                 0   
4                 0             0               0                 0   

   NGT - Incompletely Imaged  NGT - Normal  CVC - Abnormal  CVC - Borderline  \
0                          0             1               0                 0   
1                          1             0               0                 0   
2                          0             0               0                 1   
3                          0             0               1                 0   
4                          0             0               0                 0   

   CVC - Normal  Swan Ganz Catheter Present  PatientID  
0             0                           0  ec89415d1  
1             1                           0  bf4c6da3c  
2             0                           0  3fc1c97e5  
3             0                           0  c31019814  
4             1                           0  207685cd1

In [24]:
columns = train_df.columns[1:-1].to_list()
columns

['ETT - Abnormal',
 'ETT - Borderline',
 'ETT - Normal',
 'NGT - Abnormal',
 'NGT - Borderline',
 'NGT - Incompletely Imaged',
 'NGT - Normal',
 'CVC - Abnormal',
 'CVC - Borderline',
 'CVC - Normal',
 'Swan Ganz Catheter Present']

In [25]:
d = {}
for col in columns:
    d[col] = train_df[train_df[col] == 1]['StudyInstanceUID'].to_list()
d['None'] = train_df[train_df.iloc[:, 1:-1].sum(1) == 0]['StudyInstanceUID'].to_list()

In [26]:
d['None']

['1.2.826.0.1.3680043.8.498.70556928637314908190043753509080639346',
 '1.2.826.0.1.3680043.8.498.62015824992988632734732028510878678058',
 '1.2.826.0.1.3680043.8.498.32419559375493685668844762644430268742',
 '1.2.826.0.1.3680043.8.498.29594566253802547412666405573794509996',
 '1.2.826.0.1.3680043.8.498.87060544214618912677358800066372917759',
 '1.2.826.0.1.3680043.8.498.77617913658664951057379050596538324265',
 '1.2.826.0.1.3680043.8.498.22681438984244725251540286783146340207',
 '1.2.826.0.1.3680043.8.498.76873981093833909666100955199059328203',
 '1.2.826.0.1.3680043.8.498.16289885199975270507878278461180774853',
 '1.2.826.0.1.3680043.8.498.58959974007194881910883633900120894133',
 '1.2.826.0.1.3680043.8.498.57553766290478117689691227338973153148',
 '1.2.826.0.1.3680043.8.498.12223483707517344235132707229554872826',
 '1.2.826.0.1.3680043.8.498.72598527577197250033387270423700920577',
 '1.2.826.0.1.3680043.8.498.10031131575745854404126410511882847279',
 '1.2.826.0.1.3680043.8.498.277357

In [27]:
dataset_size = len(train_df)

In [28]:
val_train_ratio = 0.1

In [29]:
val_size = int(np.floor(dataset_size * val_train_ratio))

In [30]:
val_size

3008

In [31]:
l = list(probs.items())
l

[('ETT - Abnormal', 0.001559939182117963),
 ('ETT - Borderline', 0.022471022648737238),
 ('ETT - Normal', 0.14296151491815257),
 ('NGT - Abnormal', 0.005509152301403945),
 ('NGT - Borderline', 0.010445668700511423),
 ('NGT - Incompletely Imaged', 0.054262188258989395),
 ('NGT - Normal', 0.09472187666607429),
 ('CVC - Abnormal', 0.06308867958059357),
 ('CVC - Borderline', 0.16705171494579704),
 ('CVC - Normal', 0.4210651027782714),
 ('Swan Ganz Catheter Present', 0.016389234445036826),
 ('None', 0.0004739055743143179)]

In [32]:
l.sort(reverse=False, key=lambda k_v: k_v[1])
l

[('None', 0.0004739055743143179),
 ('ETT - Abnormal', 0.001559939182117963),
 ('NGT - Abnormal', 0.005509152301403945),
 ('NGT - Borderline', 0.010445668700511423),
 ('Swan Ganz Catheter Present', 0.016389234445036826),
 ('ETT - Borderline', 0.022471022648737238),
 ('NGT - Incompletely Imaged', 0.054262188258989395),
 ('CVC - Abnormal', 0.06308867958059357),
 ('NGT - Normal', 0.09472187666607429),
 ('ETT - Normal', 0.14296151491815257),
 ('CVC - Borderline', 0.16705171494579704),
 ('CVC - Normal', 0.4210651027782714)]

In [33]:
a = []
for col, _ in l:
    a += d[col]

In [34]:
len(a), len(set(a))

(50643, 30083)

In [35]:
b = list(dict.fromkeys(a))
a[0], b[0]

('1.2.826.0.1.3680043.8.498.70556928637314908190043753509080639346',
 '1.2.826.0.1.3680043.8.498.70556928637314908190043753509080639346')

In [36]:
sorted_cols = [x[0] for x in l]
sorted_cols

['None',
 'ETT - Abnormal',
 'NGT - Abnormal',
 'NGT - Borderline',
 'Swan Ganz Catheter Present',
 'ETT - Borderline',
 'NGT - Incompletely Imaged',
 'CVC - Abnormal',
 'NGT - Normal',
 'ETT - Normal',
 'CVC - Borderline',
 'CVC - Normal']

In [37]:
s_counts = list(range(len(sorted_cols)))
position = 0
for i, s_col in enumerate(sorted_cols):
    while position < len(b) and b[position] in d[s_col]:
        position += 1
    s_counts[i] = position - np.sum(s_counts[:i])

In [38]:
s_counts

[24.0,
 79.0,
 277.0,
 526.0,
 789.0,
 968.0,
 2190.0,
 2700.0,
 3383.0,
 1373.0,
 5011.0,
 12763.0]

In [39]:
s_counts / np.sum(s_counts)

array([0.00079779, 0.00262607, 0.00920786, 0.01748496, 0.02622744,
       0.03217764, 0.07279859, 0.08975169, 0.11245554, 0.04564039,
       0.16657248, 0.42425955])

In [40]:
np.sum(s_counts)

30083.0

In [41]:
cum_sum = np.cumsum([0] + s_counts, dtype=np.int16)
cum_sum

array([    0,    24,   103,   380,   906,  1695,  2663,  4853,  7553,
       10936, 12309, 17320, 30083], dtype=int16)

In [42]:
cum_sum2 = np.cumsum([0] + s_counts[:-1], dtype=np.int16)
cum_sum2

array([    0,    24,   103,   380,   906,  1695,  2663,  4853,  7553,
       10936, 12309, 17320], dtype=int16)

In [43]:
val_counts = np.floor(np.array(s_counts)  * val_train_ratio).astype(int)
val_counts

array([   2,    7,   27,   52,   78,   96,  219,  270,  338,  137,  501,
       1276])

In [44]:
idxs = np.array(np.arange(len(train_df)))
idxs

array([    0,     1,     2, ..., 30080, 30081, 30082])

In [45]:
idxs_val = []
for i in range(len(s_counts)):
    idxs_val += list(np.random.choice(idxs[cum_sum[i]: cum_sum[i + 1]], size=val_counts[i], replace=False))
idxs_val[:10]

[18, 21, 53, 55, 98, 85, 34, 57, 90, 259]

In [46]:
np.max(idxs_val)

30076

In [47]:
idxs_train = np.ones(len(train_df))
idxs_train[idxs_val] = 0
idxs_train = list(np.nonzero(idxs_train)[0])
len(idxs_train), len(idxs_val)

(27080, 3003)

In [48]:
train_df.iloc[idxs_train]

StudyInstanceUID  ETT - Abnormal  \
0      1.2.826.0.1.3680043.8.498.26697628953273228189...               0   
1      1.2.826.0.1.3680043.8.498.46302891597398758759...               0   
2      1.2.826.0.1.3680043.8.498.23819260719748494858...               0   
3      1.2.826.0.1.3680043.8.498.68286643202323212801...               0   
4      1.2.826.0.1.3680043.8.498.10050203009225938259...               0   
...                                                  ...             ...   
30078  1.2.826.0.1.3680043.8.498.74257566841157531124...               0   
30079  1.2.826.0.1.3680043.8.498.46510939987173529969...               0   
30080  1.2.826.0.1.3680043.8.498.43173270582850645437...               0   
30081  1.2.826.0.1.3680043.8.498.95092491950130838685...               0   
30082  1.2.826.0.1.3680043.8.498.99518162226171269731...               0   

       ETT - Borderline  ETT - Normal  NGT - Abnormal  NGT - Borderline  \
0                     0             0               0                 0   
1                     0             1               0                 0   
2                     0             0               0                 0   
3                     0             0               0                 0   
4                     0             0               0                 0   
...                 ...           ...             ...               ...   
30078                 0             1               0                 0   
30079                 0             0               0                 0   
30080                 0             1               0                 0   
30081                 0             0               0                 0   
30082                 0             1               0                 0   

       NGT - Incompletely Imaged  NGT - Normal  CVC - Abnormal  \
0                              0             1               0   
1                              1             0               0   
2                              0             0               0   
3                              0             0               1   
4                              0             0               0   
...                          ...           ...             ...   
30078                          0             0               0   
30079                          0             0               0   
30080                          1             0               1   
30081                          0             0               0   
30082                          0             0               0   

       CVC - Borderline  CVC - Normal  Swan Ganz Catheter Present  PatientID  
0                     0             0                           0  ec89415d1  
1                     0             1                           0  bf4c6da3c  
2                     1             0                           0  3fc1c97e5  
3                     0             0                           0  c31019814  
4                     0             1                           0  207685cd1  
...                 ...           ...                         ...        ...  
30078                 1             1                           0  5b5b9ac30  
30079                 0             1                           0  7192404d8  
30080                 0             1                           0  d4d1b066d  
30081                 1             0                           0  01a6602b8  
30082                 0             1                           0  e692d316c  

[27080 rows x 13 columns]

In [49]:
train_df.iloc[idxs_val]

StudyInstanceUID  ETT - Abnormal  \
18     1.2.826.0.1.3680043.8.498.12874505746046378224...               0   
21     1.2.826.0.1.3680043.8.498.43104496908194932746...               0   
53     1.2.826.0.1.3680043.8.498.33742897093668894116...               0   
55     1.2.826.0.1.3680043.8.498.78241780469611329601...               0   
98     1.2.826.0.1.3680043.8.498.40799603244084769744...               0   
...                                                  ...             ...   
19403  1.2.826.0.1.3680043.8.498.52051725640580728366...               0   
29444  1.2.826.0.1.3680043.8.498.27651530909734157713...               0   
23767  1.2.826.0.1.3680043.8.498.11111345482606267769...               0   
21500  1.2.826.0.1.3680043.8.498.98607809738335942410...               0   
23096  1.2.826.0.1.3680043.8.498.62294388044632820506...               0   

       ETT - Borderline  ETT - Normal  NGT - Abnormal  NGT - Borderline  \
18                    0             0               0                 0   
21                    0             1               0                 0   
53                    0             1               0                 0   
55                    0             0               0                 0   
98                    0             0               0                 0   
...                 ...           ...             ...               ...   
19403                 0             0               0                 0   
29444                 0             0               0                 0   
23767                 0             1               1                 0   
21500                 0             1               0                 0   
23096                 0             0               0                 0   

       NGT - Incompletely Imaged  NGT - Normal  CVC - Abnormal  \
18                             0             0               0   
21                             1             0               1   
53                             1             0               0   
55                             0             0               0   
98                             0             0               0   
...                          ...           ...             ...   
19403                          0             1               0   
29444                          0             0               0   
23767                          0             0               1   
21500                          1             0               0   
23096                          0             0               0   

       CVC - Borderline  CVC - Normal  Swan Ganz Catheter Present  PatientID  
18                    0             1                           0  d46ba6d06  
21                    0             0                           0  e43599771  
53                    1             0                           0  2bb41c720  
55                    0             1                           0  dcddeb64b  
98                    0             1                           0  e252d355a  
...                 ...           ...                         ...        ...  
19403                 1             1                           0  59d477481  
29444                 1             1                           0  c04a42c9f  
23767                 1             0                           0  e8bd2e98f  
21500                 1             0                           0  852789ca9  
23096                 0             1                           0  c7d680b89  

[3003 rows x 13 columns]

In [50]:
train_img_uids = list(train_df.iloc[idxs_train]['StudyInstanceUID'])
val_img_uids = list(train_df.iloc[idxs_val]['StudyInstanceUID'])

In [51]:
pwd

'/home/stanislaw/kaggle-competitions/ranzcr_clip/notebooks'

In [114]:
import pickle

train_val_split = {
    'train': train_img_uids,
    'val': val_img_uids
}

with open('/home/stanislaw/kaggle-competitions/ranzcr_clip/train_val_split.pkl', 'wb') as fp:
    pickle.dump(train_val_split, fp)
    


In [115]:
malpositions[0]

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [116]:
img_uids = train_df.iloc[:, 0].to_list()
malpositions = train_df.iloc[:, 1:-1].to_numpy()
targets = dict()
for i in range(len(img_uids)):
    targets[img_uids[i]] = malpositions[i]
    
with open('/home/stanislaw/kaggle-competitions/ranzcr_clip/malpositions.pkl', 'wb') as fp:
    pickle.dump(targets, fp)   